trigger:
- master

# Don't run against PRs
pr: none  

jobs:
- job: BuildJob
  displayName: 'Build application'
  strategy:
    matrix:  
      windows:  
        vmImage: windows-latest
        installer_extension: exe
      mac: 
        vmImage: macOS-latest
        installer_extension: dmg
    maxParallel: 2
  pool:
    vmImage: $(vmImage)
  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '10.x'

  - task: FileTransform@2
    displayName: 'Apply json transformation'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      xmlTransformationRules: 
      jsonTargetFiles: |
        buildconfig.json
        package.json

  - script: yarn
    displayName: 'Install dependencies'

  - script: yarn electron:build
    displayName: 'Build project'

  - task: CopyFiles@2
    displayName: 'Copy file to publish directory'
    inputs:
      SourceFolder: 'dist_electron'
      Contents: |
        *.yml
        *.$(installer_extension)
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'drop'     
      
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureRM'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: 'az storage blob upload-batch -d "electron-app-container" --account-name "$(Account)" -s "$(Build.ArtifactStagingDirectory)"'
